import type { Memorial } from "./types";

/** Shared placeholder portraits until client assets are uploaded to Sanity */
const IMG = {
  a: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=1200",
  b: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=1200",
  c: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=1200",
  d: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=1200",
  e: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=1200",
  f: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=1200",
  g: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&q=80&w=1200",
  h: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=1200",
  i: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&q=80&w=1200",
  j: "https://images.unsplash.com/photo-1552058544-f2b08422138a?auto=format&fit=crop&q=80&w=1200",
  k: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=1200",
  l: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=1200",
  m: "https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?auto=format&fit=crop&q=80&w=1200",
} as const;

function gallery(portrait: string, ...extras: string[]): string[] {
  return [portrait, ...extras];
}

export const MEMORIALS_FALLBACK: Memorial[] = [
  {
    id: "1",
    name: "PC Andrew Harper",
    rank: "Police Constable (PC)",
    force: "Thames Valley Police",
    region: "London",
    yearsServed: "1990 – 2019",
    age: 28,
    dateOfLoss: "15 AUG 2019",
    quote: "He was the bravest, funniest, and most dedicated officer we ever knew.",
    biography:
      "Andrew Harper joined Thames Valley Police with a quiet determination to serve his community. Colleagues remember him for his humour under pressure, his loyalty to his team, and his instinct to put others first.\n\nOn duty and off duty, Andrew carried the same sense of purpose — to protect people who could not protect themselves. His loss left a void that words cannot fill, but his example continues to guide those who served alongside him.",
    familyQuote:
      "He just loved helping people.\nThat was Andrew.\nHe would do anything for anyone.\nHe was our hero.",
    portraitImageUrl: IMG.a,
    gallery: gallery(IMG.a, IMG.m, IMG.d, IMG.f, IMG.c, IMG.e),
    candleCount: 2845,
    tributeCount: 1927,
    rememberedCount: 8432,
    timeline: [
      { date: "2010", title: "Joined Thames Valley Police", description: "Completed initial training and was posted to a response team covering rural Berkshire." },
      { date: "2014", title: "Roads Policing Attachment", description: "Volunteered for roads policing duties, known for calm decision-making during high-speed pursuits." },
      { date: "2017", title: "Interforce Bravery Commendation", description: "Recognised for intervening during a violent domestic incident without backup." },
      { date: "2019", title: "Remembered by the Force", description: "Honoured posthumously at a service attended by colleagues from across the UK." },
    ],
    tributes: [
      { name: "Sarah L.", relationship: "Family Member", timeAgo: "2 days ago", text: "Thinking of Andrew today and always. Thank you for your service and for being you." },
      { name: "James R.", relationship: "Serving Officer", timeAgo: "3 days ago", text: "We will never forget you, brother. Rest easy." },
      { name: "Emma T.", relationship: "Friend", timeAgo: "4 days ago", text: "Your smile and kindness will never be forgotten." },
      { name: "Michael K.", relationship: "Colleague", timeAgo: "1 week ago", text: "An absolute honour to have served alongside you." },
    ],
  },
  {
    id: "2",
    name: "PCSO Julie James",
    rank: "PCSO",
    force: "West Midlands Police",
    region: "Midlands",
    yearsServed: "1992 – 2020",
    age: 45,
    dateOfLoss: "22 MAR 2020",
    quote: "Her smile lit up the community. She is deeply missed by everyone.",
    biography:
      "Julie James spent nearly three decades as the visible face of policing in her neighbourhood. She knew residents by name, mediated disputes before they escalated, and made young people feel seen.\n\nPCSOs rarely receive the headlines, but Julie's impact was measured in trust restored and lives quietly changed. Her community still speaks of her in the present tense.",
    familyQuote:
      "She gave everything to that community.\nThey were her extended family.\nWe are proud of every day she wore the badge.",
    portraitImageUrl: IMG.b,
    gallery: gallery(IMG.b, IMG.e, IMG.h, IMG.a, IMG.m),
    candleCount: 1927,
    tributeCount: 1456,
    rememberedCount: 6201,
    timeline: [
      { date: "1992", title: "Appointed PCSO", description: "Among the first community support officers in her division." },
      { date: "2005", title: "Youth Engagement Lead", description: "Developed school outreach programmes credited with reducing antisocial behaviour." },
      { date: "2015", title: "Long Service Award", description: "Recognised for 20 years of dedicated community policing." },
      { date: "2020", title: "Community Memorial Bench", description: "Installed outside the station she patrolled for twenty-eight years." },
    ],
    tributes: [
      { name: "Helen W.", relationship: "Neighbour", timeAgo: "1 day ago", text: "Julie helped my family through our darkest year. We owe her everything." },
      { name: "Tom B.", relationship: "Colleague", timeAgo: "5 days ago", text: "The best PCSO I ever worked with. Proper policing with a human heart." },
      { name: "Priya S.", relationship: "Citizen", timeAgo: "1 week ago", text: "She made us feel safe. That is not something you forget." },
      { name: "Mark D.", relationship: "Supervisor", timeAgo: "2 weeks ago", text: "Julie set the standard for what community policing should be." },
    ],
  },
  {
    id: "3",
    name: "PC Liam O'Brien",
    rank: "Police Constable (PC)",
    force: "Greater Manchester Police",
    region: "North",
    yearsServed: "1985 – 2020",
    age: 52,
    dateOfLoss: "9 NOV 2020",
    quote: "A true hero who always put others before himself. Rest easy, Liam.",
    biography:
      "Liam O'Brien was a steady presence on Manchester's streets for thirty-five years. Known for de-escalating volatile situations with patience rather than force, he mentored dozens of probationers who went on to lead teams of their own.\n\nOff duty, Liam coached youth football and fundraised for officer welfare charities long before such causes were widely discussed.",
    familyQuote:
      "Dad taught us that courage is not the absence of fear — it is doing what is right anyway.",
    portraitImageUrl: IMG.c,
    gallery: gallery(IMG.c, IMG.f, IMG.k, IMG.d, IMG.l),
    candleCount: 1521,
    tributeCount: 1103,
    rememberedCount: 4890,
    timeline: [
      { date: "1985", title: "Joined GMP", description: "Posted to uniform patrol in central Manchester." },
      { date: "1998", title: "Public Order Specialist", description: "Qualified as a PSU tactician after the Euro 96 deployment." },
      { date: "2010", title: "Probationer Mentor", description: "Formalised mentoring role; credited with improving retention on his shift." },
      { date: "2020", title: "Guard of Honour", description: "Hundreds of officers lined the route at his funeral procession." },
    ],
    tributes: [
      { name: "Connor O.", relationship: "Family Member", timeAgo: "3 days ago", text: "Miss you every day, Dad. Your grandkids ask about you constantly." },
      { name: "Rachel M.", relationship: "Colleague", timeAgo: "6 days ago", text: "Liam showed me how to be an officer and a decent human being." },
      { name: "Ahmed K.", relationship: "Friend", timeAgo: "2 weeks ago", text: "Thirty years of friendship. The world is dimmer without you." },
      { name: "Supt. Greene", relationship: "Supervisor", timeAgo: "3 weeks ago", text: "A legend on our division. We strive to honour his legacy." },
    ],
  },
  {
    id: "4",
    name: "DC Matthew Boyd",
    rank: "Detective Constable (DC)",
    force: "Metropolitan Police",
    region: "London",
    yearsServed: "1979 – 2021",
    age: 58,
    dateOfLoss: "4 FEB 2021",
    quote: "His commitment to justice was unmatched. A devastating loss for the force.",
    biography:
      "Matthew Boyd spent four decades in criminal investigation, specialising in complex fraud and organised crime cases that rarely made the news but protected thousands of victims.\n\nColleagues describe meticulous case preparation, unwavering integrity, and a dry wit that kept teams grounded during exhausting investigations.",
    familyQuote:
      "Matthew believed every victim deserved someone who would not give up on them.\nThat is who he was.",
    portraitImageUrl: IMG.d,
    gallery: gallery(IMG.d, IMG.l, IMG.a, IMG.m, IMG.f),
    candleCount: 2112,
    tributeCount: 1678,
    rememberedCount: 7120,
    timeline: [
      { date: "1979", title: "Metropolitan Police Cadet", description: "Entered policing through the cadet scheme before CID attachment." },
      { date: "1992", title: "Detective Constable", description: "Transferred permanently to Economic Crime Command." },
      { date: "2008", title: "Queen's Police Medal", description: "Honoured for sustained service in major fraud investigations." },
      { date: "2021", title: "Investigation Room Dedication", description: "His team renamed their briefing room in his memory." },
    ],
    tributes: [
      { name: "DI Patel", relationship: "Colleague", timeAgo: "4 days ago", text: "The finest investigator I ever supervised. Case closed, mate — rest now." },
      { name: "Claire B.", relationship: "Family Member", timeAgo: "1 week ago", text: "Forty-two years of marriage. Still learning to live without you." },
      { name: "Jon H.", relationship: "Serving Officer", timeAgo: "2 weeks ago", text: "Boyd taught me that justice is patience as much as action." },
      { name: "Victim Support UK", relationship: "Partner", timeAgo: "1 month ago", text: "Matthew changed lives behind the scenes. We remember." },
    ],
  },
  {
    id: "5",
    name: "PC Sarah Evans",
    rank: "Police Constable (PC)",
    force: "Kent Police",
    region: "London",
    yearsServed: "1993 – 2021",
    age: 46,
    dateOfLoss: "18 JUN 2021",
    quote: "She brought kindness and empathy to every single call she answered.",
    biography:
      "Sarah Evans was the officer families hoped would arrive first — calm, compassionate, and utterly professional. She worked response and neighbourhood teams across Kent, building partnerships with domestic abuse charities and mental health crisis teams.\n\nSarah advocated quietly for better welfare support for officers dealing with repeated trauma exposure.",
    familyQuote:
      "She never came home empty-handed — always a story, always a person she was trying to help.",
    portraitImageUrl: IMG.e,
    gallery: gallery(IMG.e, IMG.b, IMG.h, IMG.a, IMG.m),
    candleCount: 1298,
    tributeCount: 987,
    rememberedCount: 4102,
    timeline: [
      { date: "1993", title: "Kent Police Recruit", description: "Graduated top of her intake for community engagement scores." },
      { date: "2008", title: "Domestic Abuse Unit", description: "Secondment supporting high-risk victim cases across the county." },
      { date: "2016", title: "Mental Health Triage Pilot", description: "Helped launch joint response with NHS crisis teams." },
      { date: "2021", title: "Charity Run in Her Name", description: "Annual 5K raises funds for officer mental health services." },
    ],
    tributes: [
      { name: "Lisa M.", relationship: "Friend", timeAgo: "2 days ago", text: "Sarah saved my life twice — once as a friend, once as an officer." },
      { name: "PC Walsh", relationship: "Colleague", timeAgo: "5 days ago", text: "Partner on the worst shifts. She made them bearable." },
      { name: "Refuge Kent", relationship: "Partner", timeAgo: "1 week ago", text: "Sarah's work changed outcomes for hundreds of families." },
      { name: "Daniel E.", relationship: "Family Member", timeAgo: "2 weeks ago", text: "Proud of you always, Sis." },
    ],
  },
  {
    id: "6",
    name: "PC David Whyte",
    rank: "Police Constable (PC)",
    force: "Police Scotland",
    region: "Scotland",
    yearsServed: "1987 – 2021",
    age: 54,
    dateOfLoss: "11 SEP 2021",
    quote: "A steadfast friend and an incredible father. We will never forget you.",
    biography:
      "David Whyte patrolled the Highlands and Glasgow with equal dedication — a rural beat officer who understood that distance and weather were part of the job, not excuses.\n\nFather of three, pipe band member, and the colleague everyone called when a situation needed steady hands rather than loud voices.",
    familyQuote:
      "He taught us that service is a privilege, not a burden.\nWe hear his voice in every decision we make.",
    portraitImageUrl: IMG.f,
    gallery: gallery(IMG.f, IMG.c, IMG.k, IMG.d, IMG.i),
    candleCount: 1744,
    tributeCount: 1320,
    rememberedCount: 5560,
    timeline: [
      { date: "1987", title: "Joined Strathclyde Police", description: "Posted to Glasgow South before transfer to Highland Division." },
      { date: "2001", title: "Mountain Rescue Liaison", description: "Coordinated police response for upland search operations." },
      { date: "2013", title: "Police Scotland Merger", description: "Selected to mentor officers through force integration." },
      { date: "2021", title: "Memorial Pipe Salute", description: "His band played at a national remembrance service in Edinburgh." },
    ],
    tributes: [
      { name: "Fiona W.", relationship: "Family Member", timeAgo: "1 day ago", text: "The children lit a candle for you tonight, David. As we do every week." },
      { name: "Sgt. MacLeod", relationship: "Colleague", timeAgo: "4 days ago", text: "Highland policing lost one of its finest. Slàinte mhath, David." },
      { name: "Hamish T.", relationship: "Friend", timeAgo: "1 week ago", text: "Thirty years in the band together. The silence is deafening." },
      { name: "Calum R.", relationship: "Serving Officer", timeAgo: "2 weeks ago", text: "You showed me what Scottish policing at its best looks like." },
    ],
  },
  {
    id: "7",
    name: "PCSO Morgan Smith",
    rank: "PCSO",
    force: "Hampshire Police",
    region: "London",
    yearsServed: "1994 – 2022",
    age: 44,
    dateOfLoss: "7 JAN 2022",
    quote: "Morgan had a gift for bringing people together. He leaves a massive void.",
    biography:
      "Morgan Smith believed visibility was prevention. He walked the same estates daily until residents waved rather than flinched, until shopkeepers saved him a cup of tea, until teenagers asked his advice instead of running.\n\nHis suicide prevention work with local charities was cited in a Home Office community policing review.",
    familyQuote:
      "Morgan never saw a stranger — only someone he had not met yet.",
    portraitImageUrl: IMG.g,
    gallery: gallery(IMG.g, IMG.j, IMG.c, IMG.f, IMG.m),
    candleCount: 1105,
    tributeCount: 834,
    rememberedCount: 3620,
    timeline: [
      { date: "1994", title: "Hampshire PCSO", description: "Assigned to Southampton city centre foot patrol." },
      { date: "2006", title: "Community Cohesion Forum", description: "Founded interfaith neighbourhood meetings after the London attacks." },
      { date: "2018", title: "Suicide Prevention Award", description: "Recognised by Samaritans for intervention training delivered to retailers." },
      { date: "2022", title: "Community Garden Memorial", description: "Residents planted a remembrance garden on his beat." },
    ],
    tributes: [
      { name: "Rev. James", relationship: "Citizen", timeAgo: "3 days ago", text: "Morgan bridged divides nobody else could reach. A peacemaker." },
      { name: "Kelly P.", relationship: "Colleague", timeAgo: "1 week ago", text: "Every PCSO aspires to be Morgan. None of us quite manage it." },
      { name: "Tyler, 19", relationship: "Citizen", timeAgo: "2 weeks ago", text: "You stopped me going down a bad road. I am at university because of you." },
      { name: "Anne S.", relationship: "Family Member", timeAgo: "3 weeks ago", text: "Our gentle giant. The world needed more of you." },
    ],
  },
  {
    id: "8",
    name: "DC Chloe Lewis",
    rank: "Detective Constable (DC)",
    force: "West Yorkshire Police",
    region: "North",
    yearsServed: "1988 – 2022",
    age: 50,
    dateOfLoss: "29 APR 2022",
    quote: "Brilliant, sharp, and fiercely protective of her team. We lost one of the best.",
    biography:
      "Chloe Lewis broke barriers as one of the first women in her division's serious crime unit. She led cold-case reviews that gave families answers decades later and fought institutional inertia with facts and relentless preparation.\n\nAway from work, Chloe was a marathon runner who raised thousands for police charities.",
    familyQuote:
      "She told us to be brave enough to ask for help.\nWe wish she had felt able to do the same.",
    portraitImageUrl: IMG.h,
    gallery: gallery(IMG.h, IMG.b, IMG.e, IMG.d, IMG.l),
    candleCount: 943,
    tributeCount: 712,
    rememberedCount: 2980,
    timeline: [
      { date: "1988", title: "West Yorkshire Police", description: "Uniform patrol in Leeds before CID selection." },
      { date: "2003", title: "Cold Case Review Team", description: "Reopened seventeen unsolved cases; six resulted in convictions." },
      { date: "2014", title: "Marathon for Mind", description: "Raised £48,000 for officer mental health charities in a single year." },
      { date: "2022", title: "Memorial Lecture Series", description: "Force established an annual lecture on investigative ethics in her name." },
    ],
    tributes: [
      { name: "DI Shah", relationship: "Colleague", timeAgo: "2 days ago", text: "Chloe was the brain and the backbone of our unit. Irreplaceable." },
      { name: "Emma L.", relationship: "Friend", timeAgo: "6 days ago", text: "Running partner, case partner, life partner in friendship. Miss you." },
      { name: "Cold Case Unit", relationship: "Colleague", timeAgo: "2 weeks ago", text: "We finish every review in your name, Chloe." },
      { name: "Robert H.", relationship: "Family Member", timeAgo: "1 month ago", text: "Daughter, sister, hero. Our family is broken but proud." },
    ],
  },
  {
    id: "9",
    name: "PC John Atkinson",
    rank: "Police Constable (PC)",
    force: "Northumbria Police",
    region: "North",
    yearsServed: "1970 – 2022",
    age: 68,
    dateOfLoss: "14 OCT 2022",
    quote: "John was the heart and soul of our shift. His legacy will endure forever.",
    biography:
      "John Atkinson served for fifty-two years — a rare full-career officer who witnessed policing transform from pocket notebooks to body-worn video. He refused promotion twice, preferring the street to the office.\n\nGenerations of Northumbria officers cite John as the reason they stayed in policing during their hardest years.",
    familyQuote:
      "Fifty-two years of service.\nFifty-two years of coming home tired but proud.\nWe would not change a single day.",
    portraitImageUrl: IMG.i,
    gallery: gallery(IMG.i, IMG.f, IMG.k, IMG.c, IMG.l),
    candleCount: 856,
    tributeCount: 645,
    rememberedCount: 3210,
    timeline: [
      { date: "1970", title: "Joined Northumbria Police", description: "Beat officer in Newcastle before the force reorganisation." },
      { date: "1995", title: "Golden Jubilee Medal", description: "Twenty-five years of unblemished service." },
      { date: "2015", title: "Fiftieth Anniversary", description: "Only a handful of officers nationally reached this milestone." },
      { date: "2022", title: "Guard of Honour — Newcastle", description: "Over four hundred officers formed a corridor at St Nicholas Cathedral." },
    ],
    tributes: [
      { name: "Chief Constable W.", relationship: "Supervisor", timeAgo: "1 week ago", text: "Half a century of policing excellence. A national treasure." },
      { name: "PC Adams", relationship: "Colleague", timeAgo: "2 weeks ago", text: "John trained my father and then trained me. Two generations." },
      { name: "Margaret A.", relationship: "Family Member", timeAgo: "3 weeks ago", text: "My husband, my rock. The station was his second home." },
      { name: "Newcastle East NPT", relationship: "Colleague", timeAgo: "1 month ago", text: "The shift is not the same. It never will be." },
    ],
  },
  {
    id: "10",
    name: "PCSO Kevin Jones",
    rank: "PCSO",
    force: "Essex Police",
    region: "London",
    yearsServed: "1986 – 2023",
    age: 55,
    dateOfLoss: "3 MAR 2023",
    quote: "Always quick with a joke and even quicker to help those in need.",
    biography:
      "Kevin Jones brought levity to long shifts and seriousness to the moments that mattered. Essex communities knew his laugh before they saw his uniform — and trusted him completely when trouble came.\n\nHe ran after-school clubs that kept hundreds of teenagers off the streets and out of gang recruitment.",
    familyQuote:
      "He made people laugh so they would not have to cry alone.\nThat was Kevin's gift.",
    portraitImageUrl: IMG.j,
    gallery: gallery(IMG.j, IMG.g, IMG.c, IMG.f, IMG.m),
    candleCount: 1202,
    tributeCount: 901,
    rememberedCount: 4450,
    timeline: [
      { date: "1986", title: "Civilian Detention Officer", description: "Transitioned to PCSO role when the scheme launched nationally." },
      { date: "2000", title: "Youth Club Founder", description: "Established free Friday night sessions in Colchester." },
      { date: "2012", title: "Anti-Gangs Taskforce Liaison", description: "Bridged community intelligence and covert operations." },
      { date: "2023", title: "Youth Centre Renaming", description: "The Kev Jones Centre opened six months after his passing." },
    ],
    tributes: [
      { name: "Jayden, 22", relationship: "Citizen", timeAgo: "4 days ago", text: "Kev got me off the estate and into an apprenticeship. Forever grateful." },
      { name: "Sue J.", relationship: "Family Member", timeAgo: "1 week ago", text: "The jokes have stopped but the love has not." },
      { name: "Insp. Doyle", relationship: "Supervisor", timeAgo: "2 weeks ago", text: "Community policing with a pulse. That was Kevin." },
      { name: "Colchester NPT", relationship: "Colleague", timeAgo: "3 weeks ago", text: "We still quote his one-liners on night shift. Keeps us going." },
    ],
  },
  {
    id: "11",
    name: "PC Mark Collins",
    rank: "Police Constable (PC)",
    force: "South Yorkshire Police",
    region: "North",
    yearsServed: "1985 – 2023",
    age: 56,
    dateOfLoss: "21 JUL 2023",
    quote: "He wore the uniform with immense pride and unwavering integrity.",
    biography:
      "Mark Collins was a Sheffield response officer who treated every call as if the person on the other end was family. He survived two serious assaults on duty and returned both times — not from stubbornness, but from conviction.\n\nMark campaigned locally for better PPE and single-crew safety protocols after colleagues were injured.",
    familyQuote:
      "Integrity was not a word he preached — it was how he lived.",
    portraitImageUrl: IMG.k,
    gallery: gallery(IMG.k, IMG.c, IMG.f, IMG.i, IMG.d),
    candleCount: 1412,
    tributeCount: 1055,
    rememberedCount: 4780,
    timeline: [
      { date: "1985", title: "South Yorkshire Police", description: "Response team in Sheffield following the miners' era policing reforms." },
      { date: "2004", title: "Assault Recovery Return", description: "Returned to frontline duties after a six-month rehabilitation." },
      { date: "2016", title: "Safety Campaign Lead", description: "Pushed for improved stab vests and trauma kits in every vehicle." },
      { date: "2023", title: "Memorial Shield Match", description: "Annual charity football match between South Yorkshire shifts." },
    ],
    tributes: [
      { name: "PC Singh", relationship: "Colleague", timeAgo: "3 days ago", text: "Mark saved my life on a domestic call. I owe him everything." },
      { name: "Helen C.", relationship: "Family Member", timeAgo: "1 week ago", text: "Proud wife of a proud officer. Always." },
      { name: "Sheffield Federation", relationship: "Partner", timeAgo: "2 weeks ago", text: "Mark's safety campaign saved lives after his. That is legacy." },
      { name: "Dave R.", relationship: "Friend", timeAgo: "1 month ago", text: "Integrity and grit. Sheffield's finest." },
    ],
  },
  {
    id: "12",
    name: "DC Richard Hayes",
    rank: "Detective Constable (DC)",
    force: "Avon & Somerset Police",
    region: "London",
    yearsServed: "1976 – 2023",
    age: 63,
    dateOfLoss: "5 DEC 2023",
    quote: "A quiet professional whose impact was felt loudly across the entire community.",
    biography:
      "Richard Hayes investigated child exploitation cases for twenty years — work he rarely discussed at home but pursued with absolute focus. Victims' advocates describe him as the officer who believed them when no one else would.\n\nRichard retired briefly in 2019, returned as a volunteer mentor, and continued supporting survivors until his death.",
    familyQuote:
      "He carried other people's pain so they would not have to carry it alone.\nWe hope he has found peace.",
    portraitImageUrl: IMG.l,
    gallery: gallery(IMG.l, IMG.d, IMG.a, IMG.m, IMG.f),
    candleCount: 702,
    tributeCount: 534,
    rememberedCount: 2890,
    timeline: [
      { date: "1976", title: "Avon & Somerset Police", description: "Uniform duties in Bristol before CID transfer." },
      { date: "1998", title: "Child Protection Unit", description: "Dedicated the remainder of his career to safeguarding investigations." },
      { date: "2019", title: "Retirement & Return", description: "Volunteered as mentor for officers entering child abuse investigation teams." },
      { date: "2023", title: "Survivor Tribute Service", description: "Victims he helped secure convictions for attended a private remembrance." },
    ],
    tributes: [
      { name: "Anonymous", relationship: "Citizen", timeAgo: "5 days ago", text: "You believed me when I was twelve. I am thirty-eight now and free because of you." },
      { name: "DI Morgan", relationship: "Colleague", timeAgo: "2 weeks ago", text: "Richard did the hardest work in policing and never sought recognition." },
      { name: "Sarah H.", relationship: "Family Member", timeAgo: "3 weeks ago", text: "A gentle soul who faced monsters. Rest now, Richard." },
      { name: "Bristol Safeguarding Board", relationship: "Partner", timeAgo: "1 month ago", text: "His case files are still cited in training today." },
    ],
  },
  {
    id: "13",
    name: "PC Emily Davies",
    rank: "Police Constable (PC)",
    force: "Thames Valley Police",
    region: "London",
    yearsServed: "1995 – 2023",
    age: 42,
    dateOfLoss: "16 AUG 2023",
    quote: "Emily was a ray of sunshine in the darkest moments. She was our guiding light.",
    biography:
      "Emily Davies combined response policing with volunteer work for officer wellbeing charities. She organised peer support groups for colleagues under investigation stress — work born from watching friends suffer in silence.\n\nEmily's laughter was famous on her shift; her compassion was quieter but deeper.",
    familyQuote:
      "She lit up every room.\nNow we light candles to bring that light back.",
    portraitImageUrl: IMG.a,
    gallery: gallery(IMG.a, IMG.e, IMG.b, IMG.m, IMG.h),
    candleCount: 1145,
    tributeCount: 876,
    rememberedCount: 3920,
    timeline: [
      { date: "1995", title: "Thames Valley Recruit", description: "Posted to Milton Keynes response team." },
      { date: "2012", title: "Peer Support Founder", description: "Established informal welfare circles later adopted force-wide." },
      { date: "2019", title: "Wellbeing Champion Award", description: "Recognised by the Police Federation for welfare advocacy." },
      { date: "2023", title: "Emily's Light Fund", description: "Charity fund established for officers in crisis." },
    ],
    tributes: [
      { name: "PC Turner", relationship: "Colleague", timeAgo: "2 days ago", text: "Emily sat with me on my worst night. I will never forget." },
      { name: "Kate D.", relationship: "Friend", timeAgo: "1 week ago", text: "Sunshine person. The world is greyer without you." },
      { name: "Fed Rep Mills", relationship: "Colleague", timeAgo: "2 weeks ago", text: "Emily's welfare work kept officers alive. Fact." },
      { name: "James D.", relationship: "Family Member", timeAgo: "3 weeks ago", text: "Sister, friend, hero. We love you." },
    ],
  },
  {
    id: "14",
    name: "PCSO Mark Thomas",
    rank: "PCSO",
    force: "West Midlands Police",
    region: "Midlands",
    yearsServed: "1980 – 2023",
    age: 61,
    dateOfLoss: "28 NOV 2023",
    quote: "Mark knew every resident by name. The streets are emptier without him.",
    biography:
      "Mark Thomas patrolled the same Birmingham streets for forty-three years. Shopkeepers trusted him with keys; schools invited him to assemblies; elderly residents saved his direct line.\n\nWhen budget cuts threatened PCSO numbers, Mark organised community petitions that kept his team funded for another cycle.",
    familyQuote:
      "The community called him their officer.\nWe called him Dad.\nBoth were right.",
    portraitImageUrl: IMG.c,
    gallery: gallery(IMG.c, IMG.g, IMG.j, IMG.f, IMG.k),
    candleCount: 827,
    tributeCount: 612,
    rememberedCount: 3340,
    timeline: [
      { date: "1980", title: "West Midlands Police", description: "Community beat officer in Handsworth before PCSO formalisation." },
      { date: "2002", title: "Shopwatch Coordinator", description: "Linked retailers with rapid response for persistent offenders." },
      { date: "2017", title: "Community Petition Lead", description: "Mobilised 12,000 signatures to protect local PCSO posts." },
      { date: "2023", title: "Memorial Plaque — High Street", description: "Unveiled outside the post office he visited every morning." },
    ],
    tributes: [
      { name: "Mr. Patel", relationship: "Citizen", timeAgo: "6 days ago", text: "Forty years in my shop doorway. I still look up expecting to see him." },
      { name: "PCSO Team B", relationship: "Colleague", timeAgo: "2 weeks ago", text: "Mark was PCSO-ing before PCSOs existed. A pioneer." },
      { name: "Lucy T.", relationship: "Family Member", timeAgo: "3 weeks ago", text: "Dad loved his patch more than anything except us." },
      { name: "Handsworth Forum", relationship: "Citizen", timeAgo: "1 month ago", text: "Our streets were safer because Mark cared." },
    ],
  },
  {
    id: "15",
    name: "PC Sara Connor",
    rank: "Police Constable (PC)",
    force: "Greater Manchester Police",
    region: "North",
    yearsServed: "1991 – 2022",
    age: 47,
    dateOfLoss: "12 MAY 2022",
    quote: "An absolute force of nature. Sara's courage inspired us all.",
    biography:
      "Sara Connor was a firearms-trained officer who volunteered for the roles others avoided. She led with humour and led from the front — respected by specialists and neighbourhood teams alike.\n\nSara mentored women entering tactical roles and spoke openly about balancing family life with high-risk duties.",
    familyQuote:
      "She was fierce in protection and soft in love.\nWe miss both sides of her every day.",
    portraitImageUrl: IMG.b,
    gallery: gallery(IMG.b, IMG.h, IMG.e, IMG.c, IMG.d),
    candleCount: 2521,
    tributeCount: 1890,
    rememberedCount: 7650,
    timeline: [
      { date: "1991", title: "GMP Recruit", description: "Uniform patrol in Salford before specialist training." },
      { date: "2004", title: "Authorised Firearms Officer", description: "One of few women on her division's AFO roster at the time." },
      { date: "2015", title: "Women in Tactical Policing Network", description: "Co-founded a national peer network for female AFOs." },
      { date: "2022", title: "Memorial Shield Presentation", description: "Force presented a posthumous bravery award to her family." },
    ],
    tributes: [
      { name: "AFO Team 7", relationship: "Colleague", timeAgo: "1 day ago", text: "Sara had your back before you knew you needed it. Legend." },
      { name: "Michelle C.", relationship: "Family Member", timeAgo: "4 days ago", text: "Mum, officer, warrior. Our hearts are shattered." },
      { name: "Women in Policing UK", relationship: "Partner", timeAgo: "2 weeks ago", text: "Sara opened doors that stayed open because of her." },
      { name: "Insp. Boyd", relationship: "Supervisor", timeAgo: "3 weeks ago", text: "The bravest officer on my roster. Bar none." },
    ],
  },
  {
    id: "16",
    name: "DC John Smith",
    rank: "Detective Constable (DC)",
    force: "Metropolitan Police",
    region: "London",
    yearsServed: "1982 – 2021",
    age: 57,
    dateOfLoss: "30 SEP 2021",
    quote: "A brilliant investigator and a steadfast mentor to so many young officers.",
    biography:
      "John Smith spent thirty-nine years in the Met, half in homicide investigation. He was the detective sergeants called when cases stalled — known for reconstructing timelines others had abandoned.\n\nJohn trained over sixty probationer detectives and kept in touch with most of them throughout their careers.",
    familyQuote:
      "He solved puzzles for a living.\nThe hardest puzzle was why good people suffer.\nHe never stopped trying to solve that one.",
    portraitImageUrl: IMG.d,
    gallery: gallery(IMG.d, IMG.l, IMG.i, IMG.a, IMG.m),
    candleCount: 1112,
    tributeCount: 845,
    rememberedCount: 4210,
    timeline: [
      { date: "1982", title: "Metropolitan Police", description: "Uniform in South London before Homicide Unit selection." },
      { date: "1996", title: "Murder Investigation Team", description: "Led case teams on fourteen major investigations." },
      { date: "2010", title: "Detective Mentor Programme", description: "Formalised training pipeline for new CID recruits." },
      { date: "2021", title: "Memorial Bench — Scotland Yard", description: "Colleagues dedicated a bench overlooking the Thames." },
    ],
    tributes: [
      { name: "DCI Roberts", relationship: "Colleague", timeAgo: "3 days ago", text: "John taught me to follow evidence, not headlines. Best lesson I ever had." },
      { name: "Prob Class '08", relationship: "Colleague", timeAgo: "1 week ago", text: "Sixty of us owe our careers to John Smith. Sixty." },
      { name: "Patricia S.", relationship: "Family Member", timeAgo: "2 weeks ago", text: "Thirty-nine years married. Still my detective." },
      { name: "Met CID Guild", relationship: "Colleague", timeAgo: "1 month ago", text: "The mentor of mentors. Rest in peace, John." },
    ],
  },
];

export const MEMORIALS_BY_ID: Record<string, Memorial> = Object.fromEntries(
  MEMORIALS_FALLBACK.map((m) => [m.id, m])
);
