"use client";

import { Document, Page, Text, View, StyleSheet, Image, PDFViewer } from '@react-pdf/renderer';

// PDF Styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    padding: 40,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottom: '2px solid #00204A',
    paddingBottom: 20,
    alignItems: 'center',
  },
  title: {
    fontSize: 28,
    color: '#00204A',
    fontWeight: 'bold',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  officerImage: {
    width: 200,
    height: 250,
    objectFit: 'cover',
    marginBottom: 20,
    alignSelf: 'center',
  },
  section: {
    margin: 10,
    padding: 10,
  },
  text: {
    fontSize: 12,
    lineHeight: 1.6,
    color: '#1E293B',
    marginBottom: 10,
  },
  quoteBox: {
    backgroundColor: '#F8FAFC',
    padding: 20,
    borderLeft: '4px solid #2563EB',
    marginVertical: 20,
  },
  quoteText: {
    fontSize: 14,
    fontStyle: 'italic',
    color: '#0F172A',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#94A3B8',
    fontSize: 10,
    borderTop: '1px solid #E2E8F0',
    paddingTop: 10,
  }
});

// React PDF Document Component
export const BookOfCondolencePDF = ({ memorial }: { memorial: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.subtitle}>In Loving Memory</Text>
        <Text style={styles.title}>{memorial.name}</Text>
        <Text style={styles.text}>{memorial.force} • {memorial.dates}</Text>
      </View>
      
      <View style={styles.section}>
        <Text style={styles.text}>
          This book is a tribute to the life of {memorial.name}. It has been created from the memories, 
          messages and condolences shared by colleagues, friends, family and members of the policing community.
        </Text>
      </View>

      <View style={styles.quoteBox}>
        <Text style={styles.quoteText}>
          "Greater love has no one than this, that someone lay down his life for his friends."
        </Text>
      </View>

      <View style={{ marginTop: 40, alignItems: 'center' }}>
        <Text style={styles.subtitle}>Candles Lit In Remembrance</Text>
        <Text style={{ fontSize: 32, color: '#00204A', marginTop: 10, fontWeight: 'bold' }}>{memorial.candles}</Text>
      </View>

      <Text style={styles.footer}>
        Generated by It Stops Now - A movement for police wellbeing, accountability and reform.
      </Text>
    </Page>
  </Document>
);
