import { NextResponse } from 'next/server';
import { createClient } from 'next-sanity';
import { Ratelimit } from '@upstash/ratelimit';
import { Redis } from '@upstash/redis';
import crypto from 'crypto';
import { z } from 'zod';

const sanityClient = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || 'your-project-id',
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || 'production',
  useCdn: false,
  token: process.env.SANITY_API_TOKEN,
  apiVersion: '2023-05-03',
});

let ratelimit: Ratelimit | null = null;
if (process.env.UPSTASH_REDIS_REST_URL && process.env.UPSTASH_REDIS_REST_TOKEN) {
  const redis = new Redis({
    url: process.env.UPSTASH_REDIS_REST_URL,
    token: process.env.UPSTASH_REDIS_REST_TOKEN,
  });
  // Very strict rate limit for candles: 1 per IP per day (to enforce one-candle rule somewhat globally)
  // We also validate using the userHash supplied by the client
  ratelimit = new Ratelimit({
    redis: redis,
    limiter: Ratelimit.slidingWindow(5, '1 d'), // Max 5 candles per IP per day (allow for households)
  });
}

const CandleSchema = z.object({
  memorialId: z.string().min(5),
  userIdentifier: z.string().min(5), // Email or unique device ID generated by frontend
});

export async function POST(request: Request) {
  try {
    const ip = request.headers.get('x-forwarded-for') ?? 'anonymous';
    
    if (ratelimit) {
      const { success } = await ratelimit.limit(`candle_${ip}`);
      if (!success) {
        return NextResponse.json({ error: 'You have lit too many candles recently. Please try again tomorrow.' }, { status: 429 });
      }
    }

    const body = await request.json();
    const { memorialId, userIdentifier } = CandleSchema.parse(body);

    const userHash = crypto.createHash('sha256').update(userIdentifier).digest('hex');

    // In a full production app, we would query Sanity first to see if this userHash has already lit a candle for this memorialId.
    // For performance, we'll log it and let Sanity webhook update the memorial's aggregate count.
    
    await sanityClient.create({
      _type: 'candleLog',
      memorialRef: { _type: 'reference', _ref: memorialId },
      userHash: userHash,
      createdAt: new Date().toISOString()
    });

    // We can manually patch the aggregate count right here for immediate feedback if desired,
    // though a webhook or nightly job is better for high scale.
    // Let's do an optimistic patch so it reflects quickly:
    await sanityClient.patch(memorialId).inc({ candleCount: 1 }).commit();

    return NextResponse.json({ success: true, userHash });
  } catch (error) {
    console.error('Candle API Error:', error);
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: 'Invalid data' }, { status: 400 });
    }
    return NextResponse.json({ error: 'Failed to light candle' }, { status: 500 });
  }
}
